language: node_js
node_js:
- '6'
- '5'
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm run bootstrap
before-script:
  - npm run build
  - npm run lint
  - npm run flow
script:
  - npm run test
