language: node_js
node_js:
- '6'
- '5'
cache:
  directories:
    - node_modules
install:
  - npm install
  - $(npm bin)/lerna bootstrap
before_script:
  - npm run lint
  - npm run build
script:
  - npm run test
